### DISCUSSION TITLE
`error loading config: no matching creation rules found` when running `sops decrypt`

### DISCUSSION THREAD

**Discussion by poperigby** [getsops/sops#1517] [Q&A] [answered]
I'm trying to pull a specific key out of a YAML file encrypted with sops, but I'm running into trouble.

When I run `sops decrypt --extract '["key1"]["key2"]`, I get this:

```
error loading config: no matching creation rules found
```

This is my directory structure:

```
.
├── .sops.yaml
└── secrets
   └── secrets.yaml
```

This is my `.sops.yaml`:

```yaml
keys:
  - &primary age1t6gkgpufq0vssxcqrh65v8vkgcln0tvkgdsgsjramdv7lcq7e5eqwy5p7h
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *primary
```
