### DISCUSSION TITLE
How do I add multiple age keys to a path_regex in .sops.yaml?

### DISCUSSION THREAD

**Discussion by Yongbeom-Kim** [getsops/sops#1579] [Q&A] [answered]
Hi guys, I am currently trying to add multiple age public keys to a single path_regex in a .sops.yaml file.

I've tried doing the `rotate` and `updatekeys` command, but I just don't understand how I can target a path regex expression with these commands.

I've also tried updating the `.sops.yaml` file manually with the block scalar construct:

```yaml
creation_rules:
  - path_regex: .*\.env$
    age: >-
      age1a5c726yqajxf635dtvkt5pfydfg9mjf72dn458u53arjx3g5tphsxa3u3w
      age1wwaz575rrr6stntm75ckhr00eqjc9nlg6p63trfyz97gf6h8fs3sh5le8h
```

But then when I try to create a new file:
```bash
sops test.env
```

It gives this error:
```
failed to parse input as Bech32-encoded age public key: malformed recipient "age1a5c726yqajxf635dtvkt5pfydfg9mjf72dn458u53arjx3g5tphsxa3u3w age1wwaz575rrr6stntm75ckhr00eqjc9nlg6p63trfyz97gf6h8fs3sh5le8h": invalid character human-readable part: s[62]=32
```

I'm at my wits end - how do I add multiple age keys so that anyone with at least 1 of the private key can encrypt/decrypt the file? Is there something I'm missing?

**Comment by felixfontein** [comment, marked as answer]
I think you need to separate the keys by comma, not by space:
```
creation_rules:
  - path_regex: .*\.env$
    age: >-
      age1a5c726yqajxf635dtvkt5pfydfg9mjf72dn458u53arjx3g5tphsxa3u3w,age1wwaz575rrr6stntm75ckhr00eqjc9nlg6p63trfyz97gf6h8fs3sh5le8h
```

**Reply by Yongbeom-Kim** [reply]
Oh, thank you - works well.

**Comment by b4u-mw** [comment]
Better solution (because it allows comments):

```
creation_rules:
  - path_regex: talsecret\.sops\.yaml$
    key_groups:
      - age:
        # key 1
        - age1...
        # key 2
        - age1...
```

This uses a key group with 1 required key, so each key works and it's yaml rather than a string list.

**Reply by felixfontein** [reply]
Since version 3.11.0 (61d9403264578b5ec26771c208f3dfb1ab63b1e8) you can also specify a list for `age` without using `key_groups`:
```yaml
creation_rules:
  - path_regex: talsecret\.sops\.yaml$
    age:
      # key 1
      - age1...
      # key 2
      - age1...
```
