### DISCUSSION TITLE
Drop empty keys from `sops:` part in encrypted documents

### DISCUSSION THREAD

**Discussion by ChristianTackeGSI** [getsops/sops#1778] [Ideas]
First thanks for this very interesting and useful tool. Just learning it.

```yaml
---
…
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    pgp: []
```

I am currently only using age for encryption. So I have five "useless" yaml keys in the `sops:` section. I can probably delete them and things work (first tests seem to confirm that). But one `sops edit` and they're back.

Could sops be changed to not emit them?
