### DISCUSSION TITLE
need to encrypt user and password string in a yaml file using a regex

### DISCUSSION THREAD

**Discussion by GuillaumeBettayeb** [getsops/sops#964] [Q&A]
Hi everyone,

I have the following data file:
```
[..]
data:
  admin-user: admin
  admin-password: SomeSecurePasswordHere
```
  
I need to encrypt the admin-user and admin-password values with sops. 

my .sops config file is:
```
---
creation_rules:
  - path_regex: values.*.yaml$
    kms: 'arn:aws:kms:xx-xxxx-1:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:role/kms_helm_secrets'
    encrypted_suffix: secrets
```
    
when I try encrypting in the command line with:
`sops --encrypt --unencrypted-regex '(admin-[a-z]*)' myfile.yaml `

it seems to be working, but when I try to encrypt the file itself, it fails with the following error message:

`sops metadata not found`

my question is, how can I encrypt the admin-user and admin-password strings with sops ?

thanks
