### ISSUE TITLE
"error loading config: no matching creation rules found" when using .gitattributes and .sops.yaml

### ISSUE THREAD

**Issue by steled** [getsops/sops#1201]
I'm using SOPS with a `.gitattributes` and `.sops.yaml` file.

See content of files below:

```text
# .gitattributes

secret.json filter=sops-json
secret.yaml filter=sops-yaml diff=sops-yaml
secret.yml filter=sops-yaml diff=sops-yaml
```

```yaml
# .sops.yaml

creation_rules:
  - age: >-
      age1<REDACTED>,
      age1<REDACTED>
    encrypted_regex: ^(password|metadata|privateKey)$
    path_regex: '(secret.json|test.yaml)'
```

And the config part from `.git/config` file:

```text
[filter "sops-json"]
        clean = sops --input-type json --output-type json -e /dev/stdin
        smudge = SOPS_AGE_KEY_FILE=$(pwd)/secrets/age-key.txt sops --input-type json --output-type json -d /dev/stdin
        required = true
```

I can run the commands for encrypt/decrypt as expected:

```shell
sops -e -i secret.json
SOPS_AGE_KEY_FILE=$(pwd)/secrets/age-key.txt sops -d -i secret.json
```

But when I'm using `git` to try to commit the files I always get the following error message:

```text
> git status -z -uall
error loading config: no matching creation rules found
error: external filter 'sops --input-type json --output-type json -e /dev/stdin' failed 1
error: external filter 'sops --input-type json --output-type json -e /dev/stdin' failed
fatal: secret.json: clean filter 'sops-json' failed
```

Maybe someone has an idea what's happening here.

EDIT: When I remove `path_regex: '(secret.json|test.yaml)'` from the `.sops.yaml` file it also works with git.
