### ISSUE TITLE
Sops removes quotes from keys in YAML

### ISSUE THREAD

**Issue by ogarcia** [getsops/sops#1363]
Given this simple YAML:
```yaml
key:
  "some.key": value
```

If I encrypt it with the `sops  -e -p mygpgkey --input-type yaml sample.yaml` command I get this result:
```yaml
key:
    some.key: ENC[AES256_GCM,data:LfKQ7cY=,iv:VX+5bGoqBWGGySkwsR3s94GZe+dknSUk7bUCUAKuM+U=,tag:xE38sC/15CshMjpphCYlAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    ...etc..
```

You have modified the key value and removed the quotes so the YAML becomes this:
```yaml
key:
  some:
    key: value
```
