### ISSUE TITLE
encrypted_regex for particular nodes in yaml?

### ISSUE THREAD

**Issue by craighurley** [getsops/sops#1367]
Hello,

For the given yaml, how can I write an `encrypted_regex` to only match "Default" under "B"?

```
A:
  Type: string
  Default: string

B:
  Type: string
  Default: string
```

If I use `encrypted_regex: "Default"`, it encrypts "Default" under both "A" and "B".

Version info
```
$ sops -v
sops 3.8.1 (latest)
```

Thank you.
