### ISSUE TITLE
`Invalid --set format` error when trying to set deeply nested value

### ISSUE THREAD

**Issue by sylvorg** [getsops/sops#1375]
Hello!

Using the following command on Windows 11:

```
sops --input-type yaml --output-type yaml --age [...] --set '["apps"]["tls"]["automation"]["policies"][0]["issuers"][0]["challeneges"]["dns"]["provider"] "api_token"' \\wsl.localhost\NixOS\mnt\wsl\sylvorg\sylvorg\caddy\argus
```

And the following yaml file `argus`:

```
admin:
  disabled: true
apps:
  [...]
  tls:
    automation:
      policies:
        - subjects:
            - '*.syvl.org'
            - syvl.org
          issuers:
            - email: jeet.ray@syvl.org
              module: acme
              challenges:
                dns:
                  provider:
                    api_token: [...]
                    name: cloudflare
```

I'm getting the error in the title; however, the `set` command seems to be following the format [here](https://github.com/getsops/sops#set-a-sub-part-in-a-document-tree).

Any help would be greatly appreciated!
