### ISSUE TITLE
How does one use `decrypt.File` provided by the mozilla sops decrypt go module

### ISSUE THREAD

**Issue by Janik-Haag** [getsops/sops#1441]
Hey I'm running into a similar error to #804
I'm opening this issue because my question is a bit different sorry if this is a duplicate.

my `.sops.yaml` basically looks like:

```yaml
keys:
  - &janik age1...
creation_rules:
  - path_regex: ^secrets/shared.yaml$
    key_groups:
      - age:
        - *janik
```

this is a minimal code example to reproduce the behavior: 
```go
package main

import (
	"fmt"
	"go.mozilla.org/sops/decrypt"
)

func main() {
	plain, err := decrypt.File("./secrets/shared.yaml", "yaml")
	if err != nil {
		fmt.Println(fmt.Errorf("Failed to decrypt: %w", err))
	}
	fmt.Println(plain)
}
```
if I run the resulting binary it prints:
```
Failed to decrypt: No keys found in file
[]
```
I also checked that XDG_CONFIG_HOME is set correctly and decrypting the file with the sops cli utility works just fine and using other tools that implement sops like https://github.com/Mic92/sops-nix/ also works without any problem. 

I also checked in the `./secrets/shared.yaml` and it basically looks like:
```yaml
...
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1...
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            ...
            -----END AGE ENCRYPTED FILE-----
...
```
