### ISSUE TITLE
VScode and AWS SSO

### ISSUE THREAD

**Issue by jdomag** [getsops/sops#1666]
Does anybody know how to configure VSCode to work with AWS SSO?
I use the config 
```
creation_rules:
  - path_regex: .*dev/secrets.yaml$
    key_groups:
      - kms:
        - arn: 'arn:aws:kms:eu-central-1:123456:alias/development-sops'
          aws_profile: development
```
And manual encryption/decryption works fine, however it breaks VSCode extension: https://github.com/signageos/vscode-sops

I can't make it work with above profile. 
How to use SOPS with VSCode and AWS SSO in an elegant way?
