### ISSUE TITLE
Request for skipping keys in YAML that match encrypted_regex but are in plaintext

### ISSUE THREAD

**Issue by vlasov-y** [getsops/sops#1680]
Hi! Issue comes from [Flux](https://github.com/fluxcd/kustomize-controller/pull/1286#discussion_r1840096168)
SOPS fails if we have keys with plain text, but those keys match *encrypted_regex*.
Can you please make SOPS to ignore fields if they are not acttualy encrypted?

Example manifest:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: main
      image: nginx:stable-alpine
      env:
        - name: ENC[AES256_GCM,data:...
          value: ENC[AES256_GCM,data:...
      resources:
        limits:
          memory: 50Mi
          cpu: 50m
    - name: patched
      image: nginx:stable-alpine
      env:
        - name: MainEnvValueIsEncrypted
          value: but this one is not
sops:
  ...
  encrypted_regex: ^env$ # There it is
  ...
```
