### ISSUE TITLE
sops encrypts the secrets twice with the same GPG subkey

### ISSUE THREAD

**Issue by tom-kuca** [getsops/sops#1705]
I have a GPG master key with two encryption subkeys. The subkeys are stored on YubiKeys, one key per device. I want to create a secret and encrypt it with both subkeys. If I lose one of the yubikeys, I can decrypt it with the other one. 

`sops` encrypts the secret twice, but with the same key. As a result, I can decrypt it with only one of the yubi.

### How to reproduce

GPG keys  

```
------------------------------
sec#  rsa4096/0xE5D0951CD1C102EC 2015-01-17 [SC]
      Key fingerprint = AB0D 441B DE32 9A98 C0EA  8C0E E5D0 951C D1C1 02EC
uid                   [ultimate] Tomas Kuca <tomas@kuca.cz>
ssb>  cv25519/0xAB5ACCD7D2C90456 2023-05-31 [E] [expires: 2025-06-06]
ssb#  nistp384/0x3C1AE34ECB19D6BB 2024-02-15 [E] [expires: 2025-06-06]
```

.sops.yaml
```yaml

creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - pgp: 
        - 0x3C1AE34ECB19D6BB
        - 0xAB5ACCD7D2C90456
 ```

Create `secrets.yaml`:
```
$ sops secrets.yaml
```

Try to decrypt it when only the "wrong" subkey is present:

```
$ sops secrets.yaml
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  0x3C1AE34ECB19D6BB: FAILED
    - | could not decrypt data key with PGP key:
      | github.com/ProtonMail/go-crypto/openpgp error: reading PGP
      | message failed: openpgp: incorrect key; GnuPG binary error:
      | failed to decrypt sops data key with pgp: gpg: encrypted
      | with nistp384 key, ID 0x3C1AE34ECB19D6BB, created 2024-02-15
      |       "Tomas Kuca <tomas@kuca.cz>"
      | gpg: public key decryption failed: No secret key
      | gpg: decryption failed: No secret key
  
   : FAILED
    - | could not decrypt data key with PGP key:
      | github.com/ProtonMail/go-crypto/openpgp error: reading PGP
      | message failed: openpgp: incorrect key; GnuPG binary error:
      | failed to decrypt sops data key with pgp: gpg: encrypted
      | with nistp384 key, ID 0x3C1AE34ECB19D6BB, created 2024-02-15
      |       "Tomas Kuca <tomas@kuca.cz>"
      | gpg: public key decryption failed: No secret key
      | gpg: decryption failed: No secret key

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```

Note *encrypted with nistp384 key, ID 0x3C1AE34ECB19D6BB* is present for both entries. I inspected the signatures manually, they are both encrypted with the mentioned key. I expect the first entry to be encrypted with `0x3C1AE34ECB19D6BB` and the second entry to be encrytped with `0xAB5ACCD7D2C90456`.

For completeness, here are the encrypted secrets:
```yaml
hello: ENC[AES256_GCM,data:vhJ4l0i1235dGgrxV1KO+QuKU+MUmJrk8MImduQ5fcPyiRiWNZ9M5Tv/NKLfiA==,iv:ugszlLc88sWC2q9wWpqy50pph9eepm3YsrjSFHwD5L0=,tag:G0cQZCz4SA9vlf8TrD6wTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-15T22:49:32Z"
    mac: ENC[AES256_GCM,data:M4UtyKd8WYCh42o44FWGIpCHYvLZa5UFNQh0YkeB8WEcjuSsWlptMTF9ZFHSNnRbcaXY3uoGvnmnFf05/GyanaC0Lbnx6myKtRdRhXO2Hj48c+wyYDQbJ/5EFkVztQ0/LPTb0UwU1CCWSVulrh6krt0rvGLTFM0Fpdt0rtI2daw=,iv:A9KuEJ53LBKuQDz+fOhuB0nVWzhGvJqe79h7YS6a8mU=,tag:LEbjcbAmUUFyBaMAvTNZCg==,type:str]
    pgp:
        - created_at: "2024-12-15T22:49:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DPBrjTssZ1rsSAwMEj5zk3M7wOeK8ipD7fyC3ZbyUBqsgg/IInhrU8fRHlPSU
            2IM7QTRfrHjaONcUXvZciu1aSv/PbdonFdzcaPx4KoYDD0ccA5zuV0Ov3SruRUWO
            ty7CdWBoTE349siQhAaxMOfBNt7pMHEdL8W4dBxnGgoJGMbUJoCW8B6sks+1ttBr
            g8y4JjNtOPRoARBG18xzONJeAdq2FfaEKwwberewi2zj8+TmMYCxIL9oKOSTfXFg
            L+F5R3Z4NOpUmv+FgzS2K+5YNzCKoRLf7lIDWqQwsPOACsB60S1CKXJXA86LgtY3
            UmoQf3EbBUqYKTWeI9fcnA==
            =3VDO
            -----END PGP MESSAGE-----
          fp: "0x3C1AE34ECB19D6BB"
        - created_at: "2024-12-15T22:49:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hJ4DPBrjTssZ1rsSAwMEeZ8ESHCqa9n/YPNvcgc9Or+7VX3O8DTJF51vnuJrh14c
            FHdWQ+ItfE2ykf6CuozE7kKRXMs/kKQre5ihPtQkNns8Q7n7NLi51buclrDl7M/a
            V3DZzD0QwPpRJCsK17dvMOsd6cPXVyQaSQs66katIwH2dViKWn21Hgf79e2L4bY0
            USbS1eC6hfUIkK7CXwTGqNJeAaHvsn/Zg/fUuL/4eSiapdY2MVdW/lu+030Uj5sm
            kEf1rKrWVElJId55+E6HR7b3bZhPfQJ8djIXnEZKe6y3q9p5bGAHB9RftjroOgiF
            Lk1JvNbilyv+jLaoWA4YOA==
            =9MHR
            -----END PGP MESSAGE-----
          fp: "0xAB5ACCD7D2C90456"
    unencrypted_suffix: _unencrypted
    version: 3.9.1
    ```

**Comment by felixfontein** [comment]
I think this is basically the same as #1365.

**Comment by felixfontein** [comment]
As written in the other issue, the problem is that GnuPG for some reason sometimes uses another subkey when you tell it to encrypt for a specific subkey. The way around that is to append an exclamation mark to the fingerprint or key ID. Unfortunately you can't do that right now because SOPS trims fingerprints and key IDs by taking the last 16 characters, which in this case will be the last 15 characters of the fingerprint/key ID plus the exclamation mark. GnuPG rejects this as malformed.

I've created a PR (#1720) which (as suggested in the other issue by the OP) handles the exclamation mark correctly when trimming. So once the new bugfix release (3.9.3) is out, you can add a `!` to your key IDs
```yaml
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
    - pgp: 
        - 0x3C1AE34ECB19D6BB!
        - 0xAB5ACCD7D2C90456!
```
and then it should work correctly.
