### ISSUE TITLE
SOPS removes the top yaml separator

### ISSUE THREAD

**Issue by chrede88** [getsops/sops#1742]
Is there a way to stop SOPS from removing the top yaml separator (`---`)?

Here is an example showing my issue:

Before encryption:
```yaml
---
some-key: some-value
```

After encryption:
```yaml
some-key: encrypted-value
```

This is my current SOPS config file:
```yaml
creation_rules:
  - path_regex: cluster/talos/config/talsecret(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(cluster|secrets|trustdinfo|certs)$
    age: <age-key>
  - path_regex: cluster/talos/.*.ya?ml # Talos config
    input_type: yaml
    encrypted_regex: ^(token|crt|key|id|secret|secrets|secretboxEncryptionSecret|ca)$
    age: <age-key>
  - path_regex: cluster/kubernetes/.*.ya?ml # Kubernetes secrets
    input_type: yaml
    encrypted_regex: ^(data|stringData)$
    age: <age-key>

stores:
  yaml:
    indent: 2
```
