### ISSUE TITLE
encrypt a list

### ISSUE THREAD

**Issue by nicefuture2016** [getsops/sops#1760]
I have a  yaml like this:

```yaml
global:
  imageRegistry: "harbor-test.com/new-buss"
  imagePullSecrets:
    - harbor-core
  storageClass: "ceph-filesystem"
env:
  - name: log_env
    value: 'new-buss'
  - name: log_env
    value: "new-buss"
  - name: randomkey
    value: "2022-12-0815:11:10"
  - name: _JAVA_OPTIONS
    value: "-Xmx2048m -Xms2048m -Dlog_env=prod"
  - name: active_profiles
    value: prod
  - name: discovery_addr
    value: nacos-cs.nacos.svc.cluster.local:8848
  - name: label
    value: new-buss-prod
  - name: nacos_username
    value: nacos
  - name: nacos_password
    value: dsadsad2dasdsa

```

I wan to encrypt imagePullSecrets and env.nacos_username env.nacos_password only

How can i create the .sops.yaml
