### ISSUE TITLE
SOPS is released using Go version 1.23.0, which has vulnerabilities

### ISSUE THREAD

**Issue by jorn-ola-birkeland** [getsops/sops#1835]
The [release workflow](https://github.com/getsops/sops/blob/main/.github/workflows/release.yml) contains the following step for setting up Go:

```
- name: Setup Go
  uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v4.0.1
  with:
    go-version-file: go.mod
    cache: false
```
and [go.mod](https://github.com/getsops/sops/blob/main/go.mod) is currently restricting language version to 1.23.0, which consequently is used as the Go compiler version in the workflow step.

I am wondering if not the Go compiler version should be explicitly set in the release workflow, similar to the [CLI workflow](https://github.com/getsops/sops/blob/main/.github/workflows/cli.yml), for example:

```
- name: Setup Go
  uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v4.0.1
  with:
    go-version: '1.24' # or 'stable'
```

Vulnerabilities in Go 1.23.0 include (severity HIGH reported by Sysdig and Trivy):

- CVE-2024-34155
- CVE-2024-34156
- CVE-2024-34158
- CVE-2024-45336
- CVE-2024-45341
