### ISSUE TITLE
Cannot set SSH key recipients in .sops.yaml

### ISSUE THREAD

**Issue by jeslinmx** [getsops/sops#1859]
From the README:

> ...You can use SSH public keys ("ssh-ed25519 AAAA...", "ssh-rsa AAAA...") as age recipients when encrypting a file.

However, when I attempt to include a SSH public key as a recipient in `.sops.yaml`:

```
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
        - ssh-ed25519 AAAA...
```

I instead get:

```
2025/05/22 23:37:40 Syncing keys for file /.../secrets.yaml
failed to parse input as Bech32-encoded age public key: malformed recipient "ssh-ed25519 AAAA...": mixed case
```

Is this not supported in `.sops.yaml`?
