### ISSUE TITLE
Cache sops AWS role assumption locally and re-use it 

### ISSUE THREAD

**Issue by ajvb** [getsops/sops#568]
If an AWS role is configured within your sops config like so:
```
sops:
    kms:
    -   arn: arn:aws:kms:us-east-1:656532927350:key/920aff2e-c5f1-4040-943a-047fa387b27e
        role: arn:aws:iam::927034868273:role/sops-dev-xyz
```

every time sops runs it will assume this role, even though the STS token could be cached and re-used.
