### ISSUE TITLE
shamir treshold breaks env files (panic: interface conversion: interface {} is float64, not string)

### ISSUE THREAD

**Issue by cohadar** [getsops/sops#857]
sops: 3.7.1 (ubuntu)

.sops.yaml
```
creation_rules:
- shamir_threshold: 2
  key_groups:
  - pgp:
    - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - pgp:
    - YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

command:
`sops example.env`

produces:
```
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
go.mozilla.org/sops/v3/stores/dotenv.(*Store).EmitPlainFile(0x1a17488, 0xc0005d24e0, 0x1, 0x1, 0x3, 0xc0005af040, 0x8, 0x10, 0x0)
	/Users/ajvb/gocode/src/go.mozilla.org/sops/stores/dotenv/store.go:122 +0x3f6
go.mozilla.org/sops/v3/stores/dotenv.(*Store).EmitEncryptedFile(0x1a17488, 0x21816938, 0xed80b80e1, 0x0, 0x11adb59, 0xc, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/ajvb/gocode/src/go.mozilla.org/sops/stores/dotenv/store.go:107 +0x2fa
main.editTree(0x137d960, 0xc000490fc0, 0x138f380, 0x1a17488, 0x138f380, 0x1a17488, 0xc0001a4840, 0x5c, 0x0, 0xc00048d1d0, ...)
	/Users/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/edit.go:164 +0xa35
main.editExample(0x137d960, 0xc000490fc0, 0x138f380, 0x1a17488, 0x138f380, 0x1a17488, 0xc0001a4840, 0x5c, 0x0, 0xc00048d1d0, ...)
	/Users/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/edit.go:84 +0x51b
main.main.func8(0xc0001e4dc0, 0x0, 0x0)
	/Users/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/main.go:943 +0x24bc
gopkg.in/urfave/cli%2ev1.HandleAction(0xfdafa0, 0x11f8d28, 0xc0001e4dc0, 0x0, 0x0)
	/Users/ajvb/gocode/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00047c4e0, 0xc00018c000, 0x2, 0x2, 0x0, 0x0)
	/Users/ajvb/gocode/src/go.mozilla.org/sops/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5f5
main.main()
	/Users/ajvb/gocode/src/go.mozilla.org/sops/cmd/sops/main.go:987 +0x3885

```

**Comment by joshdk** [comment]
👋🏻 Hello folks,

I've also been hitting this exact issue, and can add some color to the configuration that causes it.

This first configuration defines multiple `key_groups`, and will `panic` when running `sops updatekeys`. Additionally, it there is **no** panic when running `sops --encrypt` or `sops --decrypt`.

```yaml
creation_rules:
  - path_regex: .*
    key_groups:
      - pgp:
          - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - pgp:
          - YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

Whereas this second configuration a single `key_groups` with multiple keys, and will **not** panic under any `sops` operation.

```yaml
creation_rules:
  - path_regex: .*
    key_groups:
      - pgp:
          - XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          - YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

Hopefully this help to resolve this bug. Cheers!

---

Additionally, this observation holds even if you're mixing `pgp` and `kms` (which I was). This configuration will panic:

```yaml
key_groups:
  - kms:
      - arn:aws:kms:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - pgp:
      - YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

But this configuration will not:

```yaml
key_groups:
  - kms:
      - arn:aws:kms:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    pgp: # <--- No dash before, so it's the same list item.
      - YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

**Comment by felixfontein** [comment]
#1394 should fix this (`shamir_threshold` breaking INI/DotEnv files).

**Comment by Jafner** [comment]
I am encountering this issue on version 3.9.0.  

### `.sops.yaml` and `secrets.env`
(All keys and secrets below are fabricated for this issue).
`.sops.yaml`:
```yaml
creation_rules:
  - path_regex: secrets.env
    shamir_threshold: 2
    key_groups:
      - age: # Author keys
        - 'age1u3jpgcr0hq8xf4qnu9n755a3rwunt8smllkc4anqtf3qlmhg53dssp4rfm' 
      - age: # CICD runner keys
        - 'age1k4lq8ufefhnmn9t3tpd6uktg3k6llhdmu5j5ymq4nynj6m0cpacqprh0lz'
      - age: # Deploy host key
        - 'age1sc3kvdag6n3jfj6yfw7gahs2wlm0k8yzhc4wdvm7hka5s488sdgsemfcfz' 
        - 'age1fm5p0deq7vdn9afl2xtglr632lj8msaet4n3x75dd7p7mqejw5jq4zqvns'
```

`secrets.env`
```dotenv
PASSWORD=46o7kAgA9KRrOxZOJiRGIeiyxXaZP3NQ3uwDV4BpEWxC5TAc
```

### Test 1: Encrypt dotenv file in place
Running against the `secrets.env` file directly causes the error. 
```sh
$ sops --encrypt secrets.env
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
github.com/getsops/sops/v3/stores/dotenv.(*Store).EmitPlainFile(0xc0003e2530?, {0xc000011320?, 0xc0003e23e5?, 0xc0003e23e5?})
        github.com/getsops/sops/v3/stores/dotenv/store.go:144 +0x2bf
github.com/getsops/sops/v3/stores/dotenv.(*Store).EmitEncryptedFile(_, {{{0x1fed205, 0xede5ad0aa, 0x0}, {0x13c1333, 0xc}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        github.com/getsops/sops/v3/stores/dotenv/store.go:129 +0x41c
main.encrypt({{0x15a4058, 0xc00010fbf0}, {0x15b1168, 0x1e74540}, {0x15b1168, 0x1e74540}, {0xc0004a4180, 0x3a}, {0xc0006ccad0, 0x1, ...}, ...})
        github.com/getsops/sops/v3/cmd/sops/encrypt.go:119 +0x5b5
main.main.func15(0xc0001a5080)
        github.com/getsops/sops/v3/cmd/sops/main.go:1707 +0xa58
github.com/urfave/cli.HandleAction({0x116c540?, 0x1431a10?}, 0xc0006dc1c0?)
        github.com/urfave/cli@v1.22.15/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc0006dc1c0, {0xc00003e1e0, 0x3, 0x3})
        github.com/urfave/cli@v1.22.15/app.go:286 +0x766
main.main()
        github.com/getsops/sops/v3/cmd/sops/main.go:1839 +0x6d92
```

### Test 2: Cat the dotenv file, pipe into sops 
Catting the file and running sops against stdin with the input type set to dotenv seems to work fine.
```sh
cat secrets.env | sops --encrypt --age $(cat ../../../.sops/age-author-pubkeys) --input-type dotenv /dev/stdin
{
        "PASSWORD": "ENC[AES256_GCM,data:wh+lszboGzgoewya1uZZC/jQaMyEHnwm,iv:bFmqXzpI+CT+w/VoznvyvVe2YlyfSfY0+4d2m+AoVaQ=,tag:JkhsS4gEUVaK5WH2fGN6yw==,type:str]",
        "sops": {
                "shamir_threshold": 2,
                "kms": null,
                "gcp_kms": null,
                "azure_kv": null,
                "hc_vault": null,
                "age": [
                        {
                                "recipient": "age1u3jpgcr0hq8xf4qnu9n755a3rwunt8smllkc4anqtf3qlmhg53dssp4rfm",
                                "enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXanJUWkNmODdrNmRNdnlk\nb1Z0STl3WDRrZWgwdm42UW8xUGFqVkRNUnhrCjRmTkE5UnlMajh5V2RKY3RLL3pZ\ncGRyQ2hSb3J1ZXQ4aFQrbnpxLy94T2sKLS0tIFVWc3ZjREJLUDdkR1M0d21xV1RK\neFVqSFFxSUVhVC9Lc0ZhMzR6MUZsSlkKqFkU7v8RPMYrq2IBO9JK350w1/xX6/DF\ny2jhaos8R84lWKKlG5L/KHKBYjnOGwrQZhrmdc1xdalYfeCgHB8Oqw==\n-----END AGE ENCRYPTED FILE-----\n"
                        }
                ],
                "lastmodified": "2024-08-23T18:52:37Z",
                "mac": "ENC[AES256_GCM,data:p7lhzz+x+iEwiwymvzDp871dDLXbPu4rgEMtk7rmgjBKfdie6GpHLEQzTp06ALmwous+Bk53T3HmYwEuH1GH9BG1bzf7yKKMD2cpRKqKagy3zUOjZGTRA/r1NYnqb3/XxdNP45pqd00mav+7RCSmNSGZZoMHmv7uHfadzMCebdI=,iv:Eb9zDt1Vvxfwxere7SsNeX397TjAmYW5pF5ItZdt7NM=,tag:ZLqlvOU6BPhUCMhGvw9Zcw==,type:str]",
                "pgp": null,
                "unencrypted_suffix": "_unencrypted",
                "version": "3.9.0"
        }
}
```

### Test 3: Cat the dotenv file, pipe into sops and specify output type as dotenv
Running with output type specified as dotenv seems to cause the issue.
```sh
$ cat secrets.env | sops --encrypt --age $(cat ../../../.sops/age-author-pubkeys) --input-type dotenv --output-type dotenv /dev/stdin
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
github.com/getsops/sops/v3/stores/dotenv.(*Store).EmitPlainFile(0xc000013350?, {0xc00051cca8?, 0xc000013315?, 0xc000013315?})
        github.com/getsops/sops/v3/stores/dotenv/store.go:144 +0x2bf
github.com/getsops/sops/v3/stores/dotenv.(*Store).EmitEncryptedFile(_, {{{0x3a7cbd8a, 0xede5ad206, 0x0}, {0x13c1333, 0xc}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        github.com/getsops/sops/v3/stores/dotenv/store.go:129 +0x41c
main.encrypt({{0x15a4058, 0xc0000bcba0}, {0x15b1168, 0x1e74540}, {0x15b1168, 0x1e74540}, {0x7fff91308c62, 0xa}, {0xc0004c2f90, 0x1, ...}, ...})
        github.com/getsops/sops/v3/cmd/sops/encrypt.go:119 +0x5b5
main.main.func15(0xc000198f20)
        github.com/getsops/sops/v3/cmd/sops/main.go:1707 +0xa58
github.com/urfave/cli.HandleAction({0x116c540?, 0x1431a10?}, 0xc000512380?)
        github.com/urfave/cli@v1.22.15/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc000512380, {0xc000138000, 0x9, 0x9})
        github.com/urfave/cli@v1.22.15/app.go:286 +0x766
main.main()
        github.com/getsops/sops/v3/cmd/sops/main.go:1839 +0x6d92
```

### Workaround: Operate only on stdin, using json as intermediary for encrypted contents
This issue only seems to occur when sops is run against the file directly. 

```sh
$ cat secrets.env | sops --encrypt --age $(cat ../../../.sops/age-author-pubkeys) --input-type dotenv /dev/stdin | sops --decrypt --input-type json --output-type dotenv /dev/stdin
PASSWORD=46o7kAgA9KRrOxZOJiRGIeiyxXaZP3NQ3uwDV4BpEWxC5TAc
```

With this workaround my secrets files have json-formatted encrypted content, with dotenv-formatted decrypted content. It's awkward, and makes the shape of my encrypted files less readable, but it'll get the job done.
